services:
  api:
    build: ./server
    ports:
      - 3000:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - VITE_SERVER_URL=${SERVER_URL}
      - CLIENT_URL=http://localhost:9000
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  client:
    build: ./client
    depends_on:
      - api
    ports:
      - "9000:5000"
    stdin_open: true
    tty: true
